apiVersion: v1
kind: Service
metadata:
  labels:
    data-plane: snort-ips
  name: snort-ips-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    data-plane: snort-ips
