# permissions for end users to view ipspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipspolicy-viewer-role
rules:
- apiGroups:
  - config.github.com
  resources:
  - ipspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.github.com
  resources:
  - ipspolicies/status
  verbs:
  - get
