# permissions for end users to edit ipspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipspolicy-editor-role
rules:
- apiGroups:
  - config.github.com
  resources:
  - ipspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.github.com
  resources:
  - ipspolicies/status
  verbs:
  - get
