
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - config.github.com
  resources:
  - ipspolicies
  - talosspds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.github.com
  resources:
  - ipspolicies/finalizers
  - talosspds/finalizers
  verbs:
  - update
- apiGroups:
  - config.github.com
  resources:
  - ipspolicies/status
  - talosspds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
